name: user_repository
description: Dart package which managaes the user domain
version: 1.0.0

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.2
  meta: ^1.3.0
  uuid: ^3.0.4
  http: ^0.13.3
  flutter_secure_storage: ^4.2.0
