name: user_repository
description: Dart package which managaes the user domain
version: 1.0.0

environment:
  sdk: ">=1.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.0
  meta: ^1.1.8
  uuid: ^3.0.4
  http: ^0.12.2
  flutter_secure_storage: ^3.3.4
